steps:
# Install Terraform
- name: 'hashicorp/terraform'
  args:
    - 'init'
    - '-backend=false'

# Apply Terraform configuration
- name: 'hashicorp/terraform'
  args:
    - 'apply'
    - '-auto-approve'
  env:
    - 'GOOGLE_CLOUD_KEYFILE_JSON=./key.json'

# Deploy the application to App Engine Flexible
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'app'
    - 'deploy'
    - 'main.tf'  # Path to your App Engine configuration file
  env:
    - 'GOOGLE_CLOUD_KEYFILE_JSON=./key.json'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['components', 'update']
