runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  operating_system: ubuntu22

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/advance-wavelet-398416/image1', '.']
images: ['gcr.io/advance-wavelet-398416/image1']

